name: Knowd
favicon: null
layout_spectrum: 0.75568
typography_spectrum: 0.65919
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebfffe'
    - '#071c21'
    - '#cd874c'
    - '#90491f'
    - '#00c3d5'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
