name: Knowd
favicon: null
layout_spectrum: 0.9287681507412344
typography_spectrum: 0.09811
title: 'Go Further, Faster.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07411966449581087
  lightness: 0.3230746646877378
  saturation: 0.5581047325395048
  rhythmicContrast: 0.07248414447531104
purpose: []
