name: Knowd
favicon: null
layout_spectrum: 0.73969
typography_spectrum: 0.65919
title: 'Go Further, Faster.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
